# Generated by Django 4.2.7 on 2024-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0003_remove_logo_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="keppler",
            field=models.CharField(
                blank=True,
                default="",
                max_length=240,
                null=True,
                verbose_name="URL KEPPLER",
            ),
        ),
    ]
