# Generated by Django 4.2.7 on 2024-12-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0004_config_keppler"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="base_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=240,
                null=True,
                verbose_name="URL BASE",
            ),
        ),
    ]
