# Generated by Django 5.0.3 on 2024-05-31 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brigade', '0001_initial'),
        ('poll', '0003_request_requestrecord_requestanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='brigade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='brigade.brigade'),
        ),
    ]
