# Generated by Django 5.0.3 on 2024-05-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_request_brigade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='brigade',
        ),
    ]
