# Generated by Django 4.2.7 on 2024-08-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0006_request_brigade"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="request_finish",
            field=models.DateField(
                blank=True,
                default="2024-01-01",
                null=True,
                verbose_name="Fecha finaliza",
            ),
        ),
    ]
