name: urbansensor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.1
  image_picker: ^0.8.7 
  #video_player: ^2.2.18
  video_player: ^2.9.5
  record: ^4.0.7
  path_provider: ^2.0.13
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  fl_chart: ^0.35.0
  internet_connection_checker: ^1.0.0
  sqflite: ^2.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  intl: ^0.18.0
  # Lo siguiente agrega la fuente de iconos Cupertino a tu aplicación.
  # Usar con la clase CupertinoIcons para iconos de estilo iOS.
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.0.11
  google_places_flutter: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  geocoding: ^2.0.4
  geolocator: ^14.0.0
  flutter_typeahead: ^3.1.3
  get: ^4.1.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/circulo.png
    - assets/logo2.png
    - assets/logos3.png
    - assets/logoConst.png
     